### PR TITLE
Using interface IMessageBody instead of OutgoingMessageBody/IncomingMessageBody

### PR DESCRIPTION
**Pull request by Marusyk**
Please review. Made fix according to #82 and #83 
Thank you in advance

### CODE REVIEW

**Comment by VipulM-MSFT** [comment]
Thank you making the change. @suchiagicha and @amanbha - do you have any feedback?

**Comment by suchiagicha** [comment]
@Marusyk 

We are sending buffers(OutgoingMessageBody) and receiving stream(IncomingMessageBody). In order to make this explicit in serialization interface, we are thinking different way to fix this issue. 

Here are the recommended steps:

1. Remove the IncomingMessageBody and OutgoingMessageBody dependency on IMessageBody .
2. Make IncomingMessageBody  implement IDisposable .
3 Make OutgoingMessageBody  implement IDisposable .
4. Remove IMessageBody  interface.
5. Remove GetReceivedBuffer method from OutgoingMessageBody .
6. Remove GetSendBuffers method from IncomingMessageBody .

Let us know if you are interested in making these changes.

**Comment by Marusyk** [comment]
Hello @suchiagicha,
That's a good point. Thanks. I've committed that changes. Please review

**Comment by suchiagicha** [comment]
@Marusyk 
Thinking more about it. We found one more way to fix it :) 
Using concrete classes in interface doesn't look promising.
By Splitting IMessageBody into two interface IIncomingMessageBody(having GetRecievedBuffer)  and IOutgoingMessageBody(contain GetSendBuffer) . We don't need IMessageBody then.
and have concrete classes implementing those respectively instead of IMessageBody.
Serialization interface now depends on message interfaces instead of concrete classes.
That way interfaces look more pluggable .

Let me know your thoughts .

**Comment by Marusyk** [comment]
@suchiagicha
Yeah, maybe that new interfaces makes sense for future unit tests. But it is a new abstractions and it seems that YAGNI applies. Could there be a case when we need to have a more than once implementations of OutgoingMessageBody/IncomingMessageBody? Interfaces are a tool for defining contracts between multiple subsystems of application, but we are using it only inside Remoting.  

I can think of two reasons for having an interface when there is only one implementation:
 - There is another mock implementation for unit tests.
 - The interface and the implementation are defined in different class libraries.

So, if it is for unit tests then Ok for me.  If you make decision to create a two new interfaces, I'll prepare a new changes, just let me know.

**Comment by suchiagicha** [comment]
In future if we want to add implementation for IIncomingMessageBpdy and IOutgoingMessageBody for ex: another transport. it will be easier to do it if its not a concrete class.

Sure. Please go ahead with the change

**Comment by Marusyk** [comment]
@suchiagicha 
Done. Please review

**Comment by suchiagicha** [comment]
@Marusyk  Looks good to me. Thanks for the contribution. Will merge it soon .

**Comment by amanbha** [comment]
Thanks @Marusyk  and @suchiagicha . This will be part of our 6.3 runtime release.

**Pull request merged**
