### PR TITLE
allow custom actor activator

### PR DESCRIPTION
**Pull request by grahamehorner**
changes to allow custom actor activator

### CODE REVIEW

**Comment by vturecek** [comment]
@grahamehorner sorry for the delayed response. Is this a factory for the actor factory? What sort of use cases for this did you have in mind?

**Comment by grahamehorner** [comment]
I'm think of a use case where the Actor Activation would be from an external trigger like a message queue or a file system operation.

**Comment by grahamehorner** [comment]
I'm going to possibly have a rethink and write some custom attributes similar to the azure function  bindings

**Comment by amanbha** [comment]
@grahamehorner Do you have any updates for this PR as per your last comment or can i close it for now?

**Pull request closed without merging**
