### PR TITLE
Update ActorBase.cs

### PR DESCRIPTION
**Pull request by Jm-Fox**
Added method for registering any IActorTimer. This way ActorBase implementations are not restricted to System.Threading.Timer for timers.

### CODE REVIEW

**Comment by Jm-Fox** [comment]
Should have included in the commit comment: #35

**Comment by vturecek** [comment]
@Jm-Fox sorry for the delay. Looks pretty straight-forward to me. Any particular timer implementations you had in mind?

**Comment by harahma** [comment]
@Jm-Fox Thanks for working on this. I had a look at your changes. 

When the custom timer will fire it will need some hook provided by framework to be able to dispatch its callback to execute under its owning actors' concurrency lock.

Do you have any idea in mind for this? 

I think we should split the current implementation of ActorTimer class into an abstract ActorTimerBase base class (which will provide a protected method to dispatch timer callback under concurrency lock) and a concrete class ActorTimer which derives from ActorTimerBase and implements IActorTimer.

If users wants to provide their custom implementation of IActorTimer, their implementation will inherit from ActorTimerBase class and implement IActorTimer interface and use base classes' method to dispatch timer callback.

**Comment by Jm-Fox** [comment]
Apologies for the late reply; I did not have a lot of hobby time outside of work in the past few weeks.

For my purposes, I wasn't worried about the concurrency lock. My system will be able tolerate any inconsistencies that arise from race conditions involving custom timers.

That said, I do think that it's important to be able to use the concurrency lock, so I would make that optional. Maybe have the ActorTimerBase look something like this:

```
public abstract class ActorTimerBase
{
    private readonly Func<object, Task> asyncCallback;
    private readonly ActorMethodContext methodContext;
    private readonly ActorBase owner;

    public CancellationToken CancellationToken { get; set; } = CancellationToken.None;
    public bool IgnoreConcurrencyLock { get; set; } = false;
    public object State { get; set; } = null;

    protected ActorTimerBase(ActorBase owner, Func<object, Task> asyncCallback)
    {
        this.owner = owner;
        this.asyncCallback = asyncCallback;
        this.State = state;
        this.methodContext = ActorMethodContext.CreateForTimer(asyncCallback.GetMethodInfo().Name);
    }

    // Returns true if actor is disposed
    protected bool FireCallback()
    {
        try
        {
            if (this.IgnoreConcurrencyLock)
            {
                await this.asyncCallback.Invoke(State);
            }
            else
            {
                // Copy/pasted from current ActorTimer.cs (except CancellationToken)
                await this.owner.Manager.DispatchToActorAsync(
                    this.owner.Id,
                    this.callbackMethodContext,
                    false,
                    this.DispatchTimerCallback,
                    Guid.NewGuid().ToString(),
                    true,
                    this.CancellationToken);
            }
        }
        catch (ObjectDisposedException)
        {
            return true;
        }
        return false;
    }

    // Copy/pasted from current ActorTimer.cs
    private async Task<byte[]> DispatchTimerCallback(ActorBase actor, CancellationToken cancellationToken)
    {
        if (!ReferenceEquals(actor, this.owner))
        {
            throw new ObjectDisposedException("actor");
        }
        var callback = this.asyncCallback;
        if (callback != null)
        {
            await callback(this.callbackState);
        }
        return null;
    }
}
```

Things to note:
- State is mutable
- Optional mutable CancellationToken
- Base class does not handle rescheduling. Inherited classes will call FireCallback when necessary, and determine whether or not to reschedule on their own based on the return value (and maybe the state if they so choose)
- No actual timer logic is here; IDisposable not required. The existing ActorTimer can inherit the class and provide that implementation
- Constructor only requires immutable fields. Inherited classes can choose how picky they want to be with optional fields

**Comment by amanbha** [comment]
@Jim-Fox Sorry for a delayed response on this one, we took a look at it and discussed about it and turn based concurrency is inherent to our Actor model and we can't relax this restriction as it will cause  confusion for users. Additionally it will make debugging difficult when providing support without code snippet from user as now concurrency can be bypassed for timers on demand.
So please update the PR without support for IgnoreConcurrencyLock.

**Comment by amanbha** [comment]
Closing this PR, feel free to submit again with the suggestions.

**Pull request closed without merging**
