### PR TITLE
edited comments/descriptions

### PR DESCRIPTION
**Pull request by FosterMichelle**
@rwike77 This pull request supersedes #18

### CODE REVIEW

**Comment by rwike77** [comment]
@FosterMichelle  Hi, there are still several files that have changes to // code comments.  Can you revert those changes?  Thanks.

**Comment by FosterMichelle** [comment]
@rwike77 Reverted changes to // code comments on six files.

**Comment by amanbha** [comment]
@FosterMichelle Please revert changes to src/Microsoft.ServiceFabric.Services.Remoting/SR.Designer.cs  as its an auto generated file. No changes were made to corresponding SR.resx file so this should not be modified.

**Comment by amanbha** [comment]
@FosterMichelle I am merging this, will override the auto-generated src/Microsoft.ServiceFabric.Services.Remoting/SR.Designer.cs

**Pull request merged**
